### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bilbo63** [dechamps/laplock#1]
Could you generate a new release (.exe file)?  I noticed a number of commits since the initial release and it would be nice to have a new binary to go with the new source code for those of us who don't have access to a development system.

**Comment by dechamps** [comment]
Sure. [Here you go](https://github.com/dechamps/laplock/releases/tag/laplock-0.2).

**Comment by bilbo63** [comment]
Thanks for the new binary.  It works well on my Windows 10 1809 release.
The previous executable wouldn't run.  I think the system complained about
not having some DLL (might have been vb something).

**Comment by dechamps** [comment]
Presumably the specific VC++ runtime version was missing, and your system just happens to already have the one that matches the executable I just built (v140). I should probably link the runtime statically into the executable to avoid this problem…

**Comment by bilbo63** [comment]
A statically linked binary sounds like the best solution if it doesn't
bloat the executable size too much.  If it does, you might document the
runtime version required, where to find it, and how to install.
