### ISSUE TITLE
Unable to disable it

### ISSUE THREAD

**Issue by imDustinDude** [dechamps/laplock#4]
I wanted to disable it, so I disabled it via Task Manager, and it's still locks. Can someone help me about that!? (I'm on Windows 10)

**Comment by dechamps** [comment]
If you kill the process using Task Manager, and the process is gone, then it's physically impossible for laplock to lock your computer anymore. Are you sure you haven't started multiple copies of laplock? As long as at least one of them is running it will still lock.

**Comment by imDustinDude** [comment]
Now I restarted my computer and killed the process, now it's gone.

**Comment by imDustinDude** [comment]
Thanks for trying to help though! Maybe I'll try to dev with C++ too! I'm a beginner for HTML, CSS and JS (for Web Dev).
